updated the dev installation guides
Drakkar-Software/OctoBot-Docs pull request #33
Opened 2021-11-04 20:23 UTC by techfreaque

2021-11-04 23:15 UTC, GuillaumeDSM reviewed
amazing work, thanks a lot @techfreaque

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/for-developers.md
> +# simple developer installation
```suggestion
# Tentacle developer installation
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +*   we also use [GitKraken](https://www.gitkraken.com/git-client) to easily manage
```suggestion
*   We also use [GitKraken](https://www.gitkraken.com/git-client) to easily manage
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +    OctoBot's multiple repos, this is just a quality of life
```suggestion
    OctoBot's multiple repos, this is just a quality of life improvement and is not necessary.
```
(no newline)

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +* download [Visual Studio build tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019) and install "Desktop development with C++"
```suggestion
* Download [Visual Studio build tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019) and install "Desktop development with C++"
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +* install [GCC](https://discussions.apple.com/thread/8336714)
```suggestion
* Install [GCC](https://discussions.apple.com/thread/8336714)
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +## create starting scripts in pycharm
```suggestion
## Create starting scripts in pycharm
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +* click on Add Configuration
```suggestion
* Click on Add Configuration
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +now add a new python script
```suggestion
Add a new python script
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +this script will install the OctoBot-Tentacles folder and run Octobot with all your changes applied from all repositories.
```suggestion
This script will install the OctoBot-Tentacles folder and run Octobot with all your changes applied from all repositories.
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +### install OctoBot-Tentacles and run OctoBot script
```suggestion
### Install OctoBot-Tentacles and run the OctoBot script
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +#### create the following three scripts:
```suggestion
#### Create the following three scripts:
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +## start OctoBot in pycharm
```suggestion
## Start OctoBot in pycharm
```

2021-11-04 23:15 UTC, GuillaumeDSM commented on installation/developer-installation/full-developer-installation.md
> +*   [https://github.com/Drakkar-Software/OctoBot](https://github.com/Drakkar-Software/OctoBot) (dev branch) for the
in this listing, we should remove all these newlines inside items, it creates weird line breaks

2021-11-05 07:25 UTC, Herklos requested changes
Thanks for improving OctoBot documentation!

2021-11-05 07:25 UTC, Herklos commented on SUMMARY.md
> +## Tentacles <a href="coding-1" id="coding-1"></a>
Is it working?

2021-11-05 07:25 UTC, Herklos commented on coding/tentacle-development.md
> -
?

2021-11-05 07:25 UTC, Herklos commented on guides/developer-guide.md
>  This page is referring to OctoBot in versions superior to 0.4.0.
I think we can remove it, there is no 0.3.X running anymore, what do you think @GuillaumeDSM?

2021-11-05 07:25 UTC, Herklos commented on installation/developer-installation/full-developer-installation.md
> +* ****[**Install OctoBot requirements**](https://app.gitbook.com/s/XGhS0OJcF37WFUAtCJrB/c/K2S34tUZ8NdXf7pYP47C/guides/dev-environment-setup#install-octobot-requirements)****
I don't think we should keep these links. You should have links using docs.octobot.online or just relative links

2021-11-05 07:25 UTC, Herklos commented on installation/developer-installation/full-developer-installation.md
> +![](<../../.gitbook/assets/image (1).png>)
Can you rename your image assets to have a name that matches the image content please?

2021-11-15 17:49 UTC, closed without merging